manifest:
  defaults:
    revision: v0.3.0
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # - name: mctechnology17
    #   url-base: https://github.com/mctechnology17
    # - name: janpfischer
    #   url-base: https://github.com/janpfischer
    - name: janpfischer
      url-base: https://github.com/janpfischer
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
      # revision: main
    # support nice_oled and nice_epaper
    # - name: zmk-nice-oled
    #   remote: mctechnology17
    #   revision: main
    # - name: zmk-dongle-screen
    #   remote: janpfischer
    #   revision: main
    - name: prospector-zmk-module # <--- and these
      remote: carrefinho # <---
      revision: main
      # import: true
  self:
    path: config
